"""Initial migration

Revision ID: 823bc2b78df9
Revises: ed215868e61e
Create Date: 2023-05-03 00:20:08.839512

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "823bc2b78df9"
down_revision = "ed215868e61e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("is_root", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("permissions", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
