"""Add permissions

Revision ID: ed215868e61e
Revises: 5ea96a40c8a1
Create Date: 2023-05-02 22:54:35.416789

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ed215868e61e"
down_revision = "5ea96a40c8a1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client", sa.Column("permissions", sa.ARRAY(sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client", "permissions")
    # ### end Alembic commands ###
